package arogya.UI;


import arogya_classes.NutritionFact;
import arogya_classes.Food;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import arogya_classes.NutritionFact;
import com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import javax.swing.JFrame;
import javax.swing.UIManager;
import arogya.UI.AdminUpdateSuccess;

/**
 *
 * @author ADMIN
 */
public class AddNutritionFact extends javax.swing.JFrame {
 String g;
    /**
     * Creates new form NewJFrame
     */
    public AddNutritionFact() 
    {
       setUndecorated(true);
       initComponents();
       Rectangle maximumWindowBounds = GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds();
       this.setBounds(0, 0, maximumWindowBounds.width, maximumWindowBounds.height);
       this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
   
   public void adName(String nam){
  g = nam;
   }
   String ffname;
   public void getFoodName(String fname){
   
   ffname = fname;
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        calories = new javax.swing.JLabel();
        carbs = new javax.swing.JLabel();
        protein = new javax.swing.JLabel();
        vitamin_a = new javax.swing.JLabel();
        vitamin_b = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        fat = new javax.swing.JLabel();
        vitamin_c = new javax.swing.JLabel();
        fiber = new javax.swing.JLabel();
        potasium = new javax.swing.JLabel();
        magnesium = new javax.swing.JLabel();
        sodium = new javax.swing.JLabel();
        carbsTxt = new javax.swing.JTextField();
        caloriesTxt = new javax.swing.JTextField();
        fatTxt = new javax.swing.JTextField();
        protainTxt = new javax.swing.JTextField();
        vitaminATxt = new javax.swing.JTextField();
        vitaminBTxt = new javax.swing.JTextField();
        fiberTxt = new javax.swing.JTextField();
        vitaminCTxt = new javax.swing.JTextField();
        potasiumTxt = new javax.swing.JTextField();
        magnesiumTxt = new javax.swing.JTextField();
        sodiumTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Back1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 1920));

        jPanel3.setBackground(new java.awt.Color(33, 33, 33));
        jPanel3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPanel3KeyTyped(evt);
            }
        });

        calories.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        calories.setForeground(new java.awt.Color(153, 153, 153));
        calories.setText("Calories");

        carbs.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        carbs.setForeground(new java.awt.Color(153, 153, 153));
        carbs.setText("Carbs");

        protein.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        protein.setForeground(new java.awt.Color(153, 153, 153));
        protein.setText("Protein");

        vitamin_a.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vitamin_a.setForeground(new java.awt.Color(153, 153, 153));
        vitamin_a.setText("Vitamin A");

        vitamin_b.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vitamin_b.setForeground(new java.awt.Color(153, 153, 153));
        vitamin_b.setText("Vitamin B");

        Save.setBackground(new java.awt.Color(213, 0, 0));
        Save.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Save.setForeground(new java.awt.Color(255, 255, 255));
        Save.setText("Next");
        Save.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(213, 0, 0)));
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Clear.setBackground(new java.awt.Color(0, 204, 51));
        Clear.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setText("Clear");
        Clear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        fat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fat.setForeground(new java.awt.Color(153, 153, 153));
        fat.setText("Fat");

        vitamin_c.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vitamin_c.setForeground(new java.awt.Color(153, 153, 153));
        vitamin_c.setText("Vitamin C");

        fiber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fiber.setForeground(new java.awt.Color(153, 153, 153));
        fiber.setText("Fiber");

        potasium.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        potasium.setForeground(new java.awt.Color(153, 153, 153));
        potasium.setText("Potasium");

        magnesium.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        magnesium.setForeground(new java.awt.Color(153, 153, 153));
        magnesium.setText("Magnesium");

        sodium.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sodium.setForeground(new java.awt.Color(153, 153, 153));
        sodium.setText("Sodium");

        carbsTxt.setBackground(new java.awt.Color(33, 33, 33));
        carbsTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        carbsTxt.setForeground(new java.awt.Color(255, 255, 255));
        carbsTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        carbsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carbsTxtActionPerformed(evt);
            }
        });
        carbsTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                carbsTxtKeyTyped(evt);
            }
        });

        caloriesTxt.setBackground(new java.awt.Color(33, 33, 33));
        caloriesTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        caloriesTxt.setForeground(new java.awt.Color(255, 255, 255));
        caloriesTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        caloriesTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caloriesTxtActionPerformed(evt);
            }
        });
        caloriesTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caloriesTxtKeyTyped(evt);
            }
        });

        fatTxt.setBackground(new java.awt.Color(33, 33, 33));
        fatTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        fatTxt.setForeground(new java.awt.Color(255, 255, 255));
        fatTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        fatTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatTxtActionPerformed(evt);
            }
        });
        fatTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fatTxtKeyTyped(evt);
            }
        });

        protainTxt.setBackground(new java.awt.Color(33, 33, 33));
        protainTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        protainTxt.setForeground(new java.awt.Color(255, 255, 255));
        protainTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        protainTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                protainTxtActionPerformed(evt);
            }
        });
        protainTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                protainTxtKeyTyped(evt);
            }
        });

        vitaminATxt.setBackground(new java.awt.Color(33, 33, 33));
        vitaminATxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        vitaminATxt.setForeground(new java.awt.Color(255, 255, 255));
        vitaminATxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        vitaminATxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitaminATxtActionPerformed(evt);
            }
        });
        vitaminATxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vitaminATxtKeyTyped(evt);
            }
        });

        vitaminBTxt.setBackground(new java.awt.Color(33, 33, 33));
        vitaminBTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        vitaminBTxt.setForeground(new java.awt.Color(255, 255, 255));
        vitaminBTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        vitaminBTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitaminBTxtActionPerformed(evt);
            }
        });
        vitaminBTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vitaminBTxtKeyTyped(evt);
            }
        });

        fiberTxt.setBackground(new java.awt.Color(33, 33, 33));
        fiberTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        fiberTxt.setForeground(new java.awt.Color(255, 255, 255));
        fiberTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        fiberTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiberTxtActionPerformed(evt);
            }
        });
        fiberTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fiberTxtKeyTyped(evt);
            }
        });

        vitaminCTxt.setBackground(new java.awt.Color(33, 33, 33));
        vitaminCTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        vitaminCTxt.setForeground(new java.awt.Color(255, 255, 255));
        vitaminCTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        vitaminCTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitaminCTxtActionPerformed(evt);
            }
        });
        vitaminCTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vitaminCTxtKeyTyped(evt);
            }
        });

        potasiumTxt.setBackground(new java.awt.Color(33, 33, 33));
        potasiumTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        potasiumTxt.setForeground(new java.awt.Color(255, 255, 255));
        potasiumTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        potasiumTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potasiumTxtActionPerformed(evt);
            }
        });
        potasiumTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                potasiumTxtKeyTyped(evt);
            }
        });

        magnesiumTxt.setBackground(new java.awt.Color(33, 33, 33));
        magnesiumTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        magnesiumTxt.setForeground(new java.awt.Color(255, 255, 255));
        magnesiumTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        magnesiumTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                magnesiumTxtActionPerformed(evt);
            }
        });
        magnesiumTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                magnesiumTxtKeyTyped(evt);
            }
        });

        sodiumTxt.setBackground(new java.awt.Color(33, 33, 33));
        sodiumTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        sodiumTxt.setForeground(new java.awt.Color(255, 255, 255));
        sodiumTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        sodiumTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sodiumTxtActionPerformed(evt);
            }
        });
        sodiumTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sodiumTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(vitaminBTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(vitaminATxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(protainTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fatTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(vitamin_a, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(vitamin_b, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(carbs, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(calories, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(fat, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fiber, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(potasium, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(caloriesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(protein)))
                            .addComponent(carbsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(magnesiumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(magnesium)
                            .addComponent(sodium)
                            .addComponent(sodiumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vitamin_c)
                            .addComponent(fiberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vitaminCTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(potasiumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(magnesium)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(magnesiumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sodium)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sodiumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(calories)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caloriesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carbs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carbsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(protein)
                .addGap(12, 12, 12)
                .addComponent(protainTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(vitamin_a)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vitaminATxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(vitamin_b)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vitaminBTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(vitamin_c)
                .addGap(11, 11, 11)
                .addComponent(vitaminCTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fiber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fiberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(potasium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(potasiumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jPanel2.setBackground(new java.awt.Color(213, 0, 0));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nutrition Fact");

        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(213, 0, 0));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jPanel9.setBackground(new java.awt.Color(213, 0, 0));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arogya/Icons/minimizepgg.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arogya/Icons/expandpgg.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arogya/Icons/exitpgg.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        Back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arogya/Icons/icons8-back-arrow-64.png"))); // NOI18N
        Back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Back1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back)
                    .addComponent(Back1))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Back1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Back))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 616, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(32, 32, 32))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1156, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
       // String foodName = foodTxt.getText();
        String Calories = caloriesTxt.getText();
        String Carbs = carbsTxt.getText();
        String Fat = fatTxt.getText();
        String Protein = protainTxt.getText();
        String Vitamin_a = vitaminATxt.getText();
        String Vitamin_b = vitaminBTxt.getText();
        String Vitamin_c = vitaminCTxt.getText();
        String Fiber = fiberTxt.getText();
        String Potasium = potasiumTxt.getText();
        String Magnesium = magnesiumTxt.getText();
        String Sodium = sodiumTxt.getText();
        
        NutritionFact nx = new NutritionFact();
       
        try {
            String aname=g;
            nx.insertNutritionFact(ffname,aname, Calories, Carbs, Fat, Protein, Vitamin_a, Vitamin_b, Vitamin_c, Fiber, Potasium, Magnesium, Sodium);
          this.dispose();
            //adminupdatesuc();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddNutritionFact.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddNutritionFact.class.getName()).log(Level.SEVERE, null, ex);
        }
       
     
    }//GEN-LAST:event_SaveActionPerformed

    public void adminupdatesuc(){
    AdminUpdateSuccess aus = new AdminUpdateSuccess();
    aus.setVisible(true);
    this.dispose();
    
    }
    
    
    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        {
            caloriesTxt.setText("");
            carbsTxt.setText("");
            fatTxt.setText("");
            protainTxt.setText("");
            vitaminATxt.setText("");
            vitaminBTxt.setText("");
            vitaminCTxt.setText("");
            fiberTxt.setText("");
            potasiumTxt.setText("");
            magnesiumTxt.setText("");
            sodiumTxt.setText("");
        }
    }//GEN-LAST:event_ClearActionPerformed

    private void jPanel3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel3KeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel3KeyTyped

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked

    }//GEN-LAST:event_BackMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed

    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged

    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed

    }//GEN-LAST:event_jPanel2MousePressed

    private void carbsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carbsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carbsTxtActionPerformed

    private void carbsTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carbsTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_carbsTxtKeyTyped

    private void caloriesTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caloriesTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caloriesTxtActionPerformed

    private void caloriesTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caloriesTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_caloriesTxtKeyTyped

    private void fatTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatTxtActionPerformed

    private void fatTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fatTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fatTxtKeyTyped

    private void protainTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_protainTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_protainTxtActionPerformed

    private void protainTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_protainTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_protainTxtKeyTyped

    private void vitaminATxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitaminATxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vitaminATxtActionPerformed

    private void vitaminATxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vitaminATxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_vitaminATxtKeyTyped

    private void vitaminBTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitaminBTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vitaminBTxtActionPerformed

    private void vitaminBTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vitaminBTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_vitaminBTxtKeyTyped

    private void fiberTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiberTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fiberTxtActionPerformed

    private void fiberTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fiberTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fiberTxtKeyTyped

    private void vitaminCTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitaminCTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vitaminCTxtActionPerformed

    private void vitaminCTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vitaminCTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_vitaminCTxtKeyTyped

    private void potasiumTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potasiumTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potasiumTxtActionPerformed

    private void potasiumTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_potasiumTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_potasiumTxtKeyTyped

    private void magnesiumTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_magnesiumTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_magnesiumTxtActionPerformed

    private void magnesiumTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_magnesiumTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_magnesiumTxtKeyTyped

    private void sodiumTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sodiumTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sodiumTxtActionPerformed

    private void sodiumTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sodiumTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_sodiumTxtKeyTyped

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        this.setExtendedState(AddFood.ICONIFIED);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        if (this.getExtendedState()!= AddFood.MAXIMIZED_BOTH) {
            this.setExtendedState(AddFood.MAXIMIZED_BOTH);

        }else{

            this.setSize(1280, 720);

        }
    }//GEN-LAST:event_jLabel13MousePressed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void Back1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back1MouseClicked
        this.dispose();
        new AddFood().setVisible(true);
    }//GEN-LAST:event_Back1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNutritionFact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNutritionFact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNutritionFact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNutritionFact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
                 try {
                    UIManager.setLookAndFeel(new WindowsClassicLookAndFeel());
                    new AddNutritionFact().setVisible(true);
                } catch (Exception e) {
                }}
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Back1;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Save;
    private javax.swing.JLabel calories;
    private javax.swing.JTextField caloriesTxt;
    private javax.swing.JLabel carbs;
    private javax.swing.JTextField carbsTxt;
    private javax.swing.JLabel fat;
    private javax.swing.JTextField fatTxt;
    private javax.swing.JLabel fiber;
    private javax.swing.JTextField fiberTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel magnesium;
    private javax.swing.JTextField magnesiumTxt;
    private javax.swing.JLabel potasium;
    private javax.swing.JTextField potasiumTxt;
    private javax.swing.JTextField protainTxt;
    private javax.swing.JLabel protein;
    private javax.swing.JLabel sodium;
    private javax.swing.JTextField sodiumTxt;
    private javax.swing.JTextField vitaminATxt;
    private javax.swing.JTextField vitaminBTxt;
    private javax.swing.JTextField vitaminCTxt;
    private javax.swing.JLabel vitamin_a;
    private javax.swing.JLabel vitamin_b;
    private javax.swing.JLabel vitamin_c;
    // End of variables declaration//GEN-END:variables
}
